### ISSUE TITLE
Michael Issues

### ISSUE THREAD

**Issue by mltran2177** [earldenzel/Maple-Building-Management-App#20]
![complaint](https://user-images.githubusercontent.com/61170853/77217811-a5d8b600-6afb-11ea-8fc2-540e42bfc96b.PNG)
When I click the File Complaint button or the Give Feedback button in the ComplainList Page it give me an error.

--------------------------------------------------------------------------------------------------------------

![communication](https://user-images.githubusercontent.com/61170853/77217819-aec98780-6afb-11ea-8dc0-9ceae07c74b9.PNG)
When I click the Communication button in the Content Page it give me an error

--------------------------------------------------------------------------------------------------------------

![profile](https://user-images.githubusercontent.com/61170853/77217824-b6892c00-6afb-11ea-89dc-493ad11247c3.PNG)
![view](https://user-images.githubusercontent.com/61170853/77217924-973ece80-6afc-11ea-8bd1-8b13e9f8577f.PNG)
The My Profile Page is giving me a the dewdwe@hotmail.com profile when I am logged in as michael@hotmail.com

**Comment by earldenzel** [comment]
Good find.

Side note: It is also a good idea to open multiple for multiple bugs. This way, we can pigeon-hole issues and mark them as resolved individually, when they are resolved.

**Comment by swonb** [comment]
I fixed the first one on 'account_indicator' branch.
I changed 'Complaint Page' button goes to 'ViewComplaints'(Complaint list) not 'File Complaint' because property manager cannot file complaints so it causes Null Ref error. And added a File Complaint button on ViewComplaints when the user is Tenant.

**Comment by swonb** [comment]
Plus, I removed Feedback button because currently feedback can only be added on EditComplaint when the status is 'Resolved'.
